/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=examples/cloudflare-worker/wrangler.jsonc --include-runtime=false examples/cloudflare-worker/worker-configuration.d.ts` (hash: 1630465376b151b7bffff87d23a30dbc)
interface __BaseEnv_Env {
  ARTIFACTS: Artifacts;
  STAGING_ARTIFACTS: Artifacts;
  SYNC_COORDINATOR: DurableObjectNamespace<import("./src/index").SyncCoordinator>;
  SYNC_WORKFLOW: Workflow<Parameters<import("./src/index").SyncWorkflow["run"]>[0]["payload"]>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SyncCoordinator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
