/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=examples/cloudflare-worker/wrangler.jsonc --include-runtime=false examples/cloudflare-worker/worker-configuration.d.ts` (hash: 60769d7f56d18a0e48c12bbc0337701d)
interface __BaseEnv_Env {
  ARTIFACTS: Artifacts;
  GITHUB_REPOSITORY: "elithrar/example";
  ARTIFACTS_REPOSITORY: "example";
  SYNC_COORDINATOR: DurableObjectNamespace<import("./src/index").SyncCoordinator>;
  SYNC_WORKFLOW: Workflow<Parameters<import("./src/index").SyncWorkflow["run"]>[0]["payload"]>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SyncCoordinator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GITHUB_REPOSITORY" | "ARTIFACTS_REPOSITORY">
  > {}
}
