/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=examples/cloudflare-worker/wrangler.jsonc --include-runtime=false examples/cloudflare-worker/worker-configuration.d.ts` (hash: 6e9c553e0f8ff4847497a918c31c04be)
interface __BaseEnv_Env {
  ARTIFACTS: Artifacts;
  SYNC_COORDINATOR: DurableObjectNamespace<import("./src/index").SyncCoordinator>;
  SYNC_WORKFLOW: Workflow<Parameters<import("./src/index").SyncWorkflow["run"]>[0]["payload"]>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SyncCoordinator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
